#!/usr/bin/env python3
from sklearn.feature_extraction.text import TfidfVectorizer

docs = [
    'The brown fox scares the lazy dog',
    'The red wolf cuddles the enthusiastic fox',
    'The clouds become mirrored on the surface of the lake',
    'No mountain is alone',
    'Many clouds walk along the high way'
]

voc = ['the', 'fox', 'red', 'lake', 'walk', 'mountain']

vect = TfidfVectorizer(min_df=1, use_idf=False,
                       binary=True, norm=None, ngram_range=(1, 2))
fitted = vect.fit(docs)
transformed = vect.fit_transform(docs)

print('vocabulary:')
print(vect.get_feature_names_out())
print()
print('vocabulary type:')
print(type(vect.get_feature_names_out()))
print()
print('matrix shape:')
print(transformed.shape)
print()
print('tf*idf matrix:')
print(transformed)
print()
print('matrix type:')
print(type(transformed))
